import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Footer from "../components/Footer";
import AboutImage from "../public/small_image.jpg";

const About = () => {
  return (
    <>
      <Head>
        <title>About | GPS Embroidery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-col items-start justify-start w-full pt-10 bg-header-img h-60">
        <Header />

        {/* Title */}
        <div className="container z-20 mx-auto">
          <h2 className="mt-6 text-white">About GPS Embroidery</h2>
        </div>

        {/* Overlay */}
        <div className="absolute z-10 w-full -mt-10 opacity-75 bg-gradient-to-t from-black h-60"></div>
      </header>

      <main className="py-8 bg-gray-100">
        <div className="container mx-auto">
          <p>
            GPS Embroidery is an ongoing project which aims to broaden ideas
            about who-gets-to-write-what-where in and about the British
            landscape.
          </p>
          <p>
            The title refers to the way the GPS signal to the satellites mirrors
            the to and fro of the embroidery needle, as both create their path
            across space. Embroidery is historically associated with women and
            domesticity. Embroidering with GPS subverts these traditional
            understandings, making a claim for self-expression outside the home
            and in public space, too.
          </p>
          <h4 className="spaced-header">
            The landscape as mother – a 21st century approach
          </h4>
          <p>
            I began to use this tool of imperial power as a response to ideas we
            have inherited from Romantic literature. These frequently frame the
            landscape as mother, but don’t leave much room for her as individual
            within it. In contemporary politics, these understandings still
            remain emotive (think of mother country, home office, domestic
            policy, and their recent (mis)uses).
          </p>
          <p>
            In 2016, as a way to query the reactionary politics implicitly
            justified by the phrase “as a mother” (Andrea Leadsom, 2016), I
            embroidered texts by Romantic mothers across the British landscape.
            Since 2017, I have been running GPS embroidery workshops with other
            people who mother; to talk and walk with purpose but without
            direction, enjoying the conviviality of embroidering together.
            Walking with others offers new ways of understanding them that goes
            beyond words. This is a project about shared ideas rather than
            individual perspectives. Participants have composed some texts,
            others were chosen, and all have a connection to the place where we
            embroidered them.
          </p>
          <h4 className="spaced-header">Embroidering with GPS</h4>
          <div className="float-right p-4">
            <Image
              src={AboutImage}
              width={600}
              height={255}
              alt={"An embroidery"}
            />
          </div>
          <p>
            This performance of writing slows down the process of composing
            words, drawing attention to the shapes and interrelationships of
            letters, and to the peculiarity of English spelling. The landscape
            itself weaves its way into the work, and in the interactions and
            imperfections that create these embroideries, new scripts are
            formed, and tired, worn phrases are rewritten.
          </p>
          <p>
            Eventually we will create a multiplicity of 21st century
            embroideries, legacies to pass down like the domestically-produced
            examples from the past.
          </p>
          <p>Home isn’t the only place that’s sweet.</p>
          <h4 className="spaced-header">What will you embroider?</h4>
        </div>
      </main>

      <Footer />
    </>
  );
};

export default About;
