import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Footer from "../components/Footer";

const Films = () => {
  return (
    <>
      <Head>
        <title>Films | GPS Embroidery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-col items-start justify-start w-full h-56 pt-10 bg-header-img">
        <Header />

        {/* Title */}
        <div className="container z-20 mx-auto">
          <h2 className="mt-6 text-white">Films</h2>
        </div>

        {/* Overlay */}
        <div className="absolute z-10 w-full h-56 -mt-10 opacity-75 bg-gradient-to-t from-black"></div>
      </header>

      <main className="py-12 bg-gray-100">
        <div className="container flex flex-col mx-auto">
          <div className="w-full h-auto mb-2 aspect-w-16 aspect-h-7">
            <iframe
              src={`https://player.vimeo.com/video/265057517`}
              frameBorder="0"
              width={"100%"}
              allow="autoplay; fullscreen; picture-in-picture"
              allowFullScreen
            ></iframe>
          </div>

          <div className="w-full h-auto mb-4 aspect-w-16 aspect-h-9">
            <iframe
              src={`https://player.vimeo.com/video/610975822`}
              frameBorder="0"
              width={"100%"}
              allow="autoplay; fullscreen; picture-in-picture"
              allowFullScreen
            ></iframe>
          </div>

          <div className="w-full h-auto aspect-w-16 aspect-h-9">
            <iframe
              src={`https://player.vimeo.com/video/250873341`}
              frameBorder="0"
              width={"100%"}
              allow="autoplay; fullscreen; picture-in-picture"
              allowFullScreen
            ></iframe>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
};

export default Films;
