import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GPS Embroidery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full h-screen overflow-hidden">
        <video
          autoPlay
          loop
          muted
          className="absolute object-fill w-full h-full"
        >
          <source
            src="https://petermedina.com/video/beach.mp4"
            type="video/mp4"
          />
          Your browser does not support the video tag.
          <source
            src="https://petermedina.com/video/beach.webm"
            type="video/webm"
          />
          Your browser does not support the video tag.
        </video>

        <div className="flex flex-col items-start justify-start w-full h-56 pt-10 bg-header-img">
          <Header />
        </div>
      </header>

      <Footer />
    </div>
  );
}
