import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Footer from "../components/Footer";

const Projects = () => {
  return (
    <>
      <Head>
        <title>Projects | GPS Embroidery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex flex-col items-start justify-start w-full pt-10 bg-header-img h-60">
        <Header />

        {/* Title */}
        <div className="container z-20 mx-auto">
          <h2 className="mt-6 text-white">Projects</h2>
        </div>

        {/* Overlay */}
        <div className="absolute z-10 w-full -mt-10 opacity-75 bg-gradient-to-t from-black h-60"></div>
      </header>

      <main className="py-12 bg-gray-100">
        <div className="container flex mx-auto"></div>
      </main>

      <Footer />
    </>
  );
};

export default Projects;
